# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2f6b3dbe6537f6ae3b2aa132e158f7675d2dd076cc908748b37b05987f5bc2998d8db56c71c3c016e64e62a2fb2f549bb287975e1995d835d3871500f93ed2f

test:
  secret_key_base: b15977ce9c99371750866c3ce28f4ca37f7abb66a18e00434a94286872668aafcf2c0c34c3bc7e5660a1d2be8b8fe3e470f980a6aee86654233f1b3db059731e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
